DROP TABLE T_MESSAGE_RECU;
DROP TABLE T_MESSAGE;

DROP TABLE T_UTILISATEUR;


CREATE TABLE T_UTILISATEUR(
ut_id INT AUTO_INCREMENT, 
ut_prenom VARCHAR(50),
ut_nom VARCHAR(50),
ut_mail VARCHAR(200),
ut_pseudo VARCHAR(100),
ut_sexe INT,
ut_date_naissance DATE,
ut_mdp VARCHAR(512),
ut_salt VARCHAR(128),
CONSTRAINT t_utilisateur_ut_id_pk PRIMARY KEY(ut_id)
);

CREATE TABLE T_MESSAGE(
ME_ID INT AUTO_INCREMENT,
ME_CONTENUE LONGTEXT,
ut_id INT,
CONSTRAINT t_message_me_id_pk PRIMARY KEY(ME_ID),
CONSTRAINT t_message_ut_id_fk FOREIGN KEY(ut_id) REFERENCES T_UTILISATEUR(ut_id)
);

CREATE TABLE T_MESSAGE_RECU(
ME_ID INT,
UT_ID INT,
CONSTRAINT t_message_recu_me_id_ut_id PRIMARY KEY(ME_ID,UT_ID),
CONSTRAINT t_message_recu_ut_id_fk FOREIGN KEY(ut_id) REFERENCES T_UTILISATEUR(ut_id),
CONSTRAINT t_message_recu_me_id_fk FOREIGN KEY(me_id) REFERENCES T_MESSAGE(me_id)
);

CREATE VIEW V_MESSAGE_PRIVEE AS
SELECT mr.ME_ID,ME_CONTENUE,me.UT_ID AS UT_ID_SENDER, mr.UT_ID AS UT_ID_DESTINATAIRE
FROM T_MESSAGE_RECU mr
INNER JOIN T_MESSAGE me ON mr.ME_ID = me.ut_id;

CREATE VIEW V_MESSAGE_COMMUM AS
SELECT ME_ID,ME_CONTENUE,me.UT_ID AS UT_ID_SENDER
FROM T_MESSAGE me
WHERE me_id NOT IN (SELECT ME_ID FROM T_MESSAGE_RECU);

